env-file: /home/schnouki/.config/aider/env
model-settings-file: /home/schnouki/.config/aider/model-settings.yml
read: CONVENTIONS.md

dark-mode: true
gitignore: false
auto-commits: false
cache-prompts: true
watch-files: true

model: openrouter/anthropic/claude-opus-4

lint-cmd:
  - "python: ruff check --fix && ruff format"
