# Zenburn theme for Helix
# Adapted from https://github.com/bbatsov/zenburn-emacs

# Syntax highlighting
"type" = "blue-1"
"type.builtin" = "blue-1"
"type.parameter" = "orange"
"type.enum.variant" = "fg"

"constructor" = "cyan"

"constant" = "green+4"
"constant.builtin" = "green+4"
"constant.character.escape" = "yellow"

"string" = "red"
"string.regexp" = "red"
"string.special" = "red"

"comment" = "green"
"comment.line" = "green"
"comment.block" = "green"
"comment.block.documentation" = "green+2"

"variable" = "orange"
"variable.builtin" = "fg"
"variable.parameter" = "orange"
"variable.other.member" = "orange"

"label" = "yellow"

"punctuation" = "fg"
"punctuation.delimiter" = "fg"
"punctuation.bracket" = "fg"

"keyword" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.import" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.return" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "yellow", modifiers = ["bold"] }
"keyword.operator" = { fg = "yellow", modifiers = ["bold"] }
"keyword.directive" = "blue+1"
"keyword.function" = { fg = "yellow", modifiers = ["bold"] }
"keyword.storage" = { fg = "yellow", modifiers = ["bold"] }
"keyword.storage.type" = { fg = "yellow", modifiers = ["bold"] }
"keyword.storage.modifier" = { fg = "yellow", modifiers = ["bold"] }

"operator" = "fg"

"function" = "cyan"
"function.builtin" = { fg = "fg", modifiers = ["bold"] }
"function.method" = "cyan"
"function.macro" = "yellow"
"function.special" = "yellow"

"tag" = "yellow"
"attribute" = "blue+1"

"namespace" = "blue-1"

"special" = "yellow"

"markup.heading" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.marker" = "orange"
"markup.heading.1" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.2" = { fg = "green+4", modifiers = ["bold"] }
"markup.heading.3" = { fg = "blue-1", modifiers = ["bold"] }
"markup.heading.4" = { fg = "yellow-2", modifiers = ["bold"] }
"markup.heading.5" = "cyan"
"markup.heading.6" = "green+2"
"markup.list" = "fg+1"
"markup.list.unnumbered" = "fg+1"
"markup.list.numbered" = "fg+1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow-2", underline = { style = "line" } }
"markup.link.text" = "yellow-2"
"markup.link.label" = "yellow-2"
"markup.quote" = "green+2"
"markup.raw" = "green+4"
"markup.raw.inline" = "green+4"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "magenta"

# Interface
"ui.background" = { bg = "bg" }
"ui.background.separator" = "bg-1"
"ui.cursor" = { fg = "fg", bg = "fg+1" }
"ui.cursor.normal" = { fg = "fg", bg = "fg+1" }
"ui.cursor.insert" = { fg = "bg", bg = "yellow" }
"ui.cursor.select" = { fg = "bg", bg = "blue" }
"ui.cursor.match" = { fg = "orange", bg = "bg-1", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "bg", bg = "fg+1" }
"ui.cursor.primary.normal" = { fg = "bg", bg = "fg+1" }
"ui.cursor.primary.insert" = { fg = "bg", bg = "yellow" }
"ui.cursor.primary.select" = { fg = "bg", bg = "blue" }

"ui.cursorline.primary" = { bg = "bg-05" }
"ui.cursorline.secondary" = { bg = "bg-05" }
"ui.cursorcolumn.primary" = { bg = "bg-05" }
"ui.cursorcolumn.secondary" = { bg = "bg-05" }

"ui.selection" = { bg = "bg-1" }
"ui.selection.primary" = { bg = "bg-1" }
"ui.linenr" = { fg = "bg+3", bg = "bg-05" }
"ui.linenr.selected" = { fg = "yellow-2", bg = "bg-05" }

"ui.statusline" = { fg = "green+1", bg = "bg-1" }
"ui.statusline.inactive" = { fg = "green-2", bg = "bg-05" }
"ui.statusline.normal" = { fg = "green+1", bg = "bg-1" }
"ui.statusline.insert" = { fg = "yellow", bg = "bg-1" }
"ui.statusline.select" = { fg = "blue", bg = "bg-1" }

"ui.bufferline" = { fg = "fg", bg = "bg-1" }
"ui.bufferline.active" = { fg = "fg+2", bg = "bg", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "bg-1" }

"ui.popup" = { fg = "fg", bg = "bg+1" }
"ui.popup.info" = { fg = "fg", bg = "bg+1" }
"ui.window" = "fg"
"ui.help" = { fg = "fg", bg = "bg+1" }

"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.text.inactive" = "fg-05"
"ui.text.info" = "fg"

"ui.virtual.ruler" = { bg = "bg-05" }
"ui.virtual.whitespace" = "bg+2"
"ui.virtual.indent-guide" = "bg+2"
"ui.virtual.inlay-hint" = { fg = "fg-1", bg = "bg" }
"ui.virtual.inlay-hint.parameter" = { fg = "fg-1", bg = "bg" }
"ui.virtual.inlay-hint.type" = { fg = "fg-1", bg = "bg" }
"ui.virtual.wrap" = "bg+2"
"ui.virtual.jump-label" = { fg = "bg", bg = "orange", modifiers = ["bold"] }

"ui.menu" = { fg = "fg", bg = "bg+1" }
"ui.menu.selected" = { fg = "fg", bg = "bg-1" }
"ui.menu.scroll" = { fg = "bg-1", bg = "bg+2" }

"ui.gutter" = { fg = "fg", bg = "bg+1" }
"ui.gutter.selected" = { bg = "bg-05" }

"ui.highlight" = { bg = "bg-05" }
"ui.highlight.frameline" = { bg = "red-4" }

"ui.picker.header" = { fg = "yellow", bg = "bg-1" }
"ui.picker.header.column" = { fg = "green", bg = "bg-1" }
"ui.picker.header.column.active" = { fg = "yellow", bg = "bg-1", modifiers = ["bold"] }

"ui.debug.breakpoint" = { fg = "red-1", modifiers = ["bold"] }
"ui.debug.active" = { fg = "bg", bg = "yellow" }

"warning" = { fg = "orange", modifiers = ["bold"] }
"error" = { fg = "red-1", modifiers = ["bold"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green+4", modifiers = ["bold"] }

"diagnostic" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { color = "green+2", style = "curl" } }
"diagnostic.info" = { underline = { color = "cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "orange", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { fg = "fg-1" }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
# Base colors
fg-1 = "#656555"
fg-05 = "#989890"
fg = "#DCDCCC"
"fg+1" = "#FFFFEF"
"fg+2" = "#FFFFFD"

bg-2 = "#000000"
bg-1 = "#2B2B2B"
bg-08 = "#303030"
bg-05 = "#383838"
bg = "#3F3F3F"
"bg+05" = "#494949"
"bg+1" = "#4F4F4F"
"bg+2" = "#5F5F5F"
"bg+3" = "#6F6F6F"

# Reds
red-6 = "#6C3333"
red-5 = "#7C4343"
red-4 = "#8C5353"
red-3 = "#9C6363"
red-2 = "#AC7373"
red-1 = "#BC8383"
red = "#CC9393"
"red+1" = "#DCA3A3"
"red+2" = "#ECB3B3"

# Orange
orange = "#DFAF8F"

# Yellows
yellow-2 = "#D0BF8F"
yellow-1 = "#E0CF9F"
yellow = "#F0DFAF"

# Greens
green-5 = "#2F4F2F"
green-4 = "#3F5F3F"
green-3 = "#4F6F4F"
green-2 = "#5F7F5F"
green-1 = "#6F8F6F"
green = "#7F9F7F"
"green+1" = "#8FB28F"
"green+2" = "#9FC59F"
"green+3" = "#AFD8AF"
"green+4" = "#BFEBBF"

# Cyan
cyan = "#93E0E3"

# Blues
"blue+3" = "#BDE0F3"
"blue+2" = "#ACE0E3"
"blue+1" = "#94BFF3"
blue = "#8CD0D3"
blue-1 = "#7CB8BB"
blue-2 = "#6CA0A3"
blue-3 = "#5C888B"
blue-4 = "#4C7073"
blue-5 = "#366060"

# Magenta
magenta = "#DC8CC3"
